first_name = input('Please enter your first_name:')
last_name = input('Please enter your last_name:')
print('Hello,' + first_name.capitalize() + ' ' + last_name.capitalize())
print('Hello,' + first_name.upper() +' ' + last_name.upper())
print('Hello,' + first_name.lower() +' ' + last_name.lower())